### ISSUE TITLE
Gallery not working in both iOS and android device 

### ISSUE THREAD

**Issue by sauravdpl** [camilo1498/stories_editor#19]
@camilo1498  When I click on the thumb image to open the gallery on iOS and Android devices, it shows a black screen. Also, I waited for a long time to see if it was loading. But it only showed a black screen; I am using it for my client project, so can you please fix the bug or tell me the solution?

**Comment by rabernet** [comment]
I found the problem. In Gallery_media_picker you have Model: List<PickedAssetModel> path
so... In lib/src/presentation/main_view/main_view.dart Line: 423
Change:
controlNotifier.mediaPath = path[0]['path'];
To:
controlNotifier.mediaPath = path.toString();
...
control_provider.dart
  // New imagepath

   List<PickedAssetModel> _mediaPath = [];
   List<PickedAssetModel> get mediaPath => _mediaPath;

   set mediaPath(List<PickedAssetModel> media) {
     _mediaPath = media;
     notifyListeners();
   }

....
/src/presentation/dragable_items/draggable_widget.dart

 /// image [file_image_gb.dart]
      case ItemType.image:
        if (_controlProvider.mediaPath.isNotEmpty) {

          overlayWidget = SizedBox(
            width: _size.width - 72,
            child: FileImageBG(
              //RAFAEL
              filePath: File(_controlProvider.mediaPath[0].path.toString()),
              generatedGradient: (color1, color2) {
                _colorProvider.color1 = color1;
                _colorProvider.color2 = color2;
              },
            ),
          );
        } else {
          overlayWidget = Container();
        }

**Comment by camilo1498** [comment]
this issue was fixed in new version, thanks to report it :D
