### ISSUE TITLE
iOS : thumb pictures in pick gallery & menu albums

### ISSUE THREAD

**Issue by Kinomad** [camilo1498/stories_editor#2]
Not a bug but a quick feedback on iOS to help to improve UX :)

1/ Thumb pictures (grid pick image)
When you pick an image in your gallery, each image inside the grid have a white top and bottom border. Images to pick-up aren't cropped to take full space like usually. 

2/ Menu album (dropdown directory)
The list of the album (directories) aren't order by alphanumeric or date. Usually on iOS, you have first, your Recents et Favorites default albums and after all the other album listed by alphanumeric.

**Comment by intellign** [comment]
check out my [forked version](https://github.com/intellign/stories_editor)
