### ISSUE TITLE
Problem with fontList

### ISSUE THREAD

**Issue by Kinomad** [camilo1498/stories_editor#3]
On iOS, fontList seem doesn't work or maybe I do wrong things.

I have my fonts in my pubspec.yaml and I can see and use them normally (for example with an usual style `TextStyle(fontFamily: 'MyOwnArial')`

in stories_editor, I use fontList to params my fonts :
```
fontList: const [
'MyOwnArial',
'SansFransisco',
'cartoons'
],
```

I can see a 3 selections but all have the same default style in thumb and when I use it.
What I do wrong? :)

PS: sorry to spam you Camilo :))

**Comment by camilo1498** [comment]
Hello, sorry for not replying earlier, I've been a bit busy in the last few days. I already uploaded the new changes solving the listfonts issue, the gallery interface and the action on close button.
in `fontList` now you should use `fontFamilyList: List<String> []` and `isCustomFontList: true,`

**Comment by camilo1498** [comment]
and now you don't need to use `MultiProvider()` in your `void main(){runApp(const MyApp());}`, the project use provider but now has a better implemetation

**Comment by Kinomad** [comment]
Hi Camilo, thanks for the update!
It's nice to use it without provider and to show my own font in the editor :)

For the cancel button, it's work too, much better :) It's can be nice to have a "onCancel" like you have for "onDone" to manage your own action (for example, to save your story in database, have a direct exit or your own pop-up style, etc...)

I will open a new issue for that, but on iOS, since this new update, your gallery doesn't work (you have just a black screen with the cancel button but you can't access at the photo like before). So it's not possible to access and play with images...

Thanks for your work :)
