### ISSUE TITLE
Customization Input

### ISSUE THREAD

**Issue by rlee1990** [camilo1498/stories_editor#5]
Is there a way to change the text for the share button?
Also is there a way to add support for @ and # ?

**Comment by camilo1498** [comment]
hello, at the moment it is not possible to change the text of the button, but in the next update it will be possible to customize it, and no, there's no a way to add # or @, in the future it is possible to implement it, thanks for your feedback 😁.

**Comment by rlee1990** [comment]
@camilo1498 thanks for the quick reply. I forked the project and will see if I can assist at all in adding that.
