### ISSUE TITLE
Question On Images

### ISSUE THREAD

**Issue by rlee1990** [camilo1498/stories_editor#6]
Is there a way for the image that is selected to cover the view and not have the background shown?

**Comment by camilo1498** [comment]
I don't understand your question.  
Do you want to not show the background gradient of the image or just that the image fill the entire view?
Sorry for the broken English.

**Comment by rlee1990** [comment]
@camilo1498 So I would want the option for the image to start out as full screen with the option for it to be shrunken and dragged like on Instagram.

**Comment by camilo1498** [comment]
@rlee1990 no, at the moment there is no way to do it, but it could be included later

**Comment by rlee1990** [comment]
Okay thanks

**Comment by bobooma** [comment]
[Flutter: Looking up a deactivated widget's ancestor is unsafe](https://stackoverflow.com/questions/61424636/flutter-looking-up-a-deactivated-widgets-ancestor-is-unsafe)

i got this error when try to close

**Comment by camilo1498** [comment]
it is a issue of `photo_View` => https://github.com/bluefireteam/photo_view/pull/499

when the developers update the version on `pub.dev` i will update the dependency.
